"""Model for embeddings added

Revision ID: 7e06e8840702
Revises: f1905a8654cc
Create Date: 2025-05-10 13:56:04.976979

"""
import sqlalchemy as sa

from alembic import op
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7e06e8840702'
down_revision: Union[str, None] = 'f1905a8654cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('articles',
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('chapter_name', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
