"""Chats and messages added

Revision ID: f1905a8654cc
Revises: 905acdc96da2
Create Date: 2025-04-16 17:04:56.731492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1905a8654cc'
down_revision: Union[str, None] = '905acdc96da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('messages',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('mark', sa.Enum('LIKE', 'DISLIKE', 'NONE', name='mark_enum'), nullable=False),
    sa.Column('author', sa.Enum('USER', 'SYSTEM', 'AI', name='author_enum'), nullable=False),
    sa.Column('parent_uuid', sa.UUID(), nullable=True),
    sa.Column('chat_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_uuid'], ['chats.uuid'], ),
    sa.ForeignKeyConstraint(['parent_uuid'], ['messages.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    op.execute("DROP TYPE IF EXISTS mark_enum")
    op.execute("DROP TYPE IF EXISTS author_enum")
    # ### end Alembic commands ###
